#!/usr/bin/env python3
"""The census data the build needs, from work/analysis to census/ (README
"Census data"): no cartridge bytes, so the repository can carry it.

    census/census*.ex          the instructions each census run saw execute
                               (address, count), copied as they are
    census/xe-display-lists.txt  each scene's XEGS display lists, as the
                               game selected them ($D402/$D403 in the .col
                               files: the only thing the build reads there)
    census/reloc.txt           port/reloclist.py's list with the byte
                               column "--": the build reads those bytes from
                               the cartridge (xesource.analyse)

    python port/mkcensus.py
"""
import glob
import os
import shutil

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "work", "analysis")
DST = os.path.join(HERE, "..", "census")


def main():
    os.makedirs(DST, exist_ok=True)
    for p in sorted(glob.glob(os.path.join(SRC, "census", "*.ex"))):
        shutil.copyfile(p, os.path.join(DST, os.path.basename(p)))
    used = set()
    for p in glob.glob(os.path.join(SRC, "census", "*.col")):
        lo = None
        for line in open(p):
            parts = line.split()
            if len(parts) < 5:
                continue
            s, reg, val = int(parts[0]), parts[3], int(parts[4], 16)
            if reg == "D402":
                lo = val
            elif reg == "D403" and lo is not None:
                used.add((s, val * 256 + lo))
    with open(os.path.join(DST, "xe-display-lists.txt"), "w", newline="\n") as f:
        f.write("# generated by port/mkcensus.py: scene, XEGS display list address\n")
        for s, a in sorted(used):
            f.write("%d %04X\n" % (s, a))
    with open(os.path.join(DST, "reloc.txt"), "w", newline="\n") as f:
        for line in open(os.path.join(SRC, "reloc.txt")):
            parts = line.split()
            if line.startswith("#") or len(parts) < 5:
                f.write(line)
                continue
            parts[3] = "--"
            f.write(" ".join(parts) + "\n")
    print("wrote %s" % os.path.normpath(DST))


if __name__ == "__main__":
    main()
