#!/usr/bin/env python3
"""Write probes/optable.lua (mnemonic and addressing mode for all 256 opcodes)
from the toolkit's m6502 table, for probes that decode instructions."""
import os
import sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.environ.get("A7800_TOOLKIT", os.path.join(HERE, "..", "..", "a7800-toolkit", "tools")))
import m6502  # noqa: E402

rows = ['[%d]={"%s","%s"}' % (op, m6502.OPCODES[op][0], m6502.OPCODES[op][1]) for op in range(256)]
out = os.path.join(HERE, "..", "probes", "optable.lua")
with open(out, "w") as f:
    f.write("-- generated by port/mkoptable.py from the toolkit's m6502.py\nOPT = {" + ",".join(rows) + "}\n")
print("wrote", os.path.normpath(out))
